webService/webService/webservice/clientchurn/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #path('', views.index),
path('acceuil/', views.index, name="index"),
    path('clients/', views.clients, name="clients"),
    path('analyses/', views.analyses, name="analyses"),
    path('predictions/', views.predictions, name='predictions'),
    path('resultat/', views.resultat, name="resultat"),
]

webService/webService/webservice/webservice/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include,re_path as url
from clientchurn import views
#from django.conf.urls import url

urlpatterns = [
    path('', views.index, name="index"),
    path('clientchurn/', include(("clientchurn.urls",'clientchurn'), namespace='clientchurn')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

webService/webService/webservice/clientchurn/models.py
from django.db import models

# Create your models here.

webService/webService/webservice/clientchurn/forms.py
from django.forms import ModelForm, TextInput, EmailInput
from django.forms.utils import ErrorList

from .models import Contact





class ParagraphErrorList(ErrorList):
    def __str__(self):
        return self.as_divs()
    def as_divs(self):
        if not self: return ''
        return '<div class="errorlist">%s</div>' % ''.join(['<p class="small error">%s</p>' % e for e in self])

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ["name", "email"]
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'email': EmailInput(attrs={'class': 'form-control'})
        }

webService/webService/webservice/clientchurn/views.py
from django.shortcuts import render
import pandas as pd
import os
import json
from matplotlib import pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
import names
#----------------------------------------------------------------------------------------
csv_filename = os.path.join(os.path.dirname(__file__), 'bd_Clients.csv')
maPrediction = []

index = list(range(0,50))
client = []
for i in range(50):
    a = names.get_full_name()
    client.append(a)
bdClients = pd.DataFrame({'client': client}, index = index )

df = pd.read_csv(csv_filename)
df.drop('customerID',axis='columns',inplace=True)
#Suppression des colones vide
df1 = df[df.TotalCharges!=' ']
#Conversion en numerique
df1.TotalCharges = pd.to_numeric(df1.TotalCharges)
#Remplacement des tous les No.. en No
df1.replace('No internet service','No',inplace=True)
df1.replace('No phone service','No',inplace=True)
#Conversion de Yes en 1 Et de No en 0
yes_no_columns = ['Partner','Dependents','PhoneService','MultipleLines','OnlineSecurity','OnlineBackup',
                  'DeviceProtection','TechSupport','StreamingTV','StreamingMovies','PaperlessBilling','Churn']
for col in yes_no_columns:
    df1[col].replace({'Yes': 1,'No': 0},inplace=True)
#Conversion du sexe en 1 et 0
df1['gender'].replace({'Female':1,'Male':0},inplace=True)
#Encodage de la colonne Categorie
df2 = pd.get_dummies(data=df1, columns=['InternetService','Contract','PaymentMethod'])
#Scalaire des colonnes tenure','MonthlyCharges','TotalCharges'
cols_to_scale = ['tenure','MonthlyCharges','TotalCharges']
scaler = MinMaxScaler()
df2[cols_to_scale] = scaler.fit_transform(df2[cols_to_scale])
#Definition des X et y
X = df2.drop('Churn',axis='columns')
y = df2['Churn']
#Definition des données de test et des données d'entrainements
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=5)
#Construction du modèle (ANN) avec tensorflow/keras
model = keras.Sequential([
    keras.layers.Dense(26, input_shape=(26,), activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])
# opt = keras.optimizers.Adam(learning_rate=0.01)

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

def index(request):
    json_records = bdClients.reset_index().to_json(orient='records')
    data = []
    data = json.loads(json_records)
    context = {'d': data}
    return render(request, 'clientchurn/index.html', context)

def clients(request):
    dataframe = df.iloc[:50, :]
    json_records = dataframe.reset_index().to_json(orient='records')
    data = []
    data = json.loads(json_records)
    context = {'d': data}
    return render(request, 'clientchurn/clients.html', context)

def analyses(request):
    df = pd.read_csv(csv_filename)
    df.drop('customerID', axis='columns', inplace=True)
    df1 = df[df.TotalCharges != ' ']
    tenure_churn_no = df1[df1.Churn == 'No'].tenure
    tenure_churn_yes = df1[df1.Churn == 'Yes'].tenure
    plt.plot(tenure_churn_no, label='tenure')
    plt.plot(tenure_churn_yes, label='Number Of Customers')
    plt.legend()
    context = {'plot_div': plt.show()}
    return render(request, 'clientchurn/analyses.html', context)

def predictions(request):
    return render(request, 'clientchurn/predictions.html')

def resultat(request):
    maPrediction.clear()
    custumer_id = request.GET.get('custumer_id')
    print(custumer_id)
    def predict_churn(custumer):
        custumer_to_predict = custumer
        test_pred_custumer = model.predict(custumer)
        print("le resulat de l'algorithm est",test_pred_custumer)
        y_pred = []
        if test_pred_custumer > 0.5:
            y_pred.append(1)
            prediction = "Ce client va partir si on optimise pas les services auquels il est abonné."
        else:
            y_pred.append(0)
            prediction = "Ce client va rester car les services porposés sont pour le moment bien optimisé"
        print("l'arrondi du resultat est:", y_pred)
        return prediction
    prediction = predict_churn(X_test.iloc[[custumer_id]])
    maPrediction.append(prediction)
    print('La prédiction est:', maPrediction)
    print("l'id du client est :", custumer_id)
    context = {
        'prediction': prediction
    }
    return render(request, 'clientchurn/predictions.html', context)

webService/webService/webservice/clientchurn/templates/clientchurn/analyses.html
{% extends 'clientchurn/base.html' %}

{% block content %}

    {% autoescape off %}
        {{ plot_div }}
    {% endautoescape %}}

{% endblock %}

webService/webService/webservice/clientchurn/templates/clientchurn/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>client Churn Prediction - APP</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'clientchurn/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'clientchurn/css/clientchurn.css' %}" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="brand"><a href="/">Client Churn Prediction - APP</a></div>
    <div class="address-bar">Notre Web Service de prediction du depart des clients (CCPA) est une application Web qui se base sur les habitudes des clients pour predire leurs comportement grace à des algorithmes d'inteligence Artificielle. </div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Client Churn Prediction - APP</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'clientchurn:index' %}">Acceuil</a>
                    </li>
                    <li>
                        <a href="{% url 'clientchurn:clients' %}">Informations Clients et Différents Service</a>
                    </li>
                    <!-- <li>
                        <a href="{% url 'clientchurn:analyses' %}">Analyse Client</a>
                    </li>-->
                    <li>
                        <a href="{% url 'clientchurn:predictions' %}">Faire un prevision</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <div class="container">
      <div class="row">
        <div class="box">
            {% block content %}  {% endblock %}
        </div>
      </div>
    </div>


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; <a href="https://www.linkedin.com/in/christin-yessoufou-20169119b/" target="_blank">Christin YESSOUFOU</a>  -   <a href="#" target="_blank">CCPA</a></p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'clientchurn/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'clientchurn/js/bootstrap.min.js' %}"></script>

  </body>
</html>

webService/webService/webservice/clientchurn/templates/clientchurn/clients.html
{% extends 'clientchurn/base.html' %}

{% block content %}


    <div class="container table-responsive fixed-table-body">
  <h2 class="text-center"><u> Apperçu des Informations des 50 premiers Clients</u></h2><br>
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>gender</th>
        <th>SeniorCitizen</th>
        <th>Partner</th>
        <th>Dependents</th>
        <th>tenure</th>
          <th>PhoneService</th>
        <th>MultipleLines</th>
        <th>InternetService</th>
        <th>OnlineSecurity</th>
        <th>OnlineBackup'</th>
          <th>DeviceProtection</th>
        <th>TechSupport</th>
        <th>StreamingTV</th>
        <th>StreamingMovies</th>
        <th>Contract</th>
          <th>PaperlessBilling</th>
        <th>PaymentMethod</th>
        <th>MonthlyCharges</th>
        <th>TotalCharges</th>
      </tr>
    </thead>
    <tbody>
    <!-- jinja2 Technique -->
    {% if d %}
    {% for i in d %}
      <tr>
        <td>{{i.gender}}</td>
        <td>{{i.SeniorCitizen}}</td>
        <td>{{i.Partner}}</td>
        <td>{{i.Dependents}}</td>
        <td>{{i.tenure}}</td>
        <td>{{i.PhoneService}}</td>
        <td>{{i.MultipleLines}}</td>
        <td>{{i.InternetService}}</td>
        <td>{{i.OnlineSecurity}}</td>
        <td>{{i.OnlineBackup}}</td>
        <td>{{i.DeviceProtection}}</td>
        <td>{{i.TechSupport}}</td>
        <td>{{i.StreamingTV}}</td>
        <td>{{i.StreamingMovies}}</td>
        <td>{{i.Contract}}</td>
        <td>{{i.PaperlessBilling}}</td>
        <td>{{i.PaymentMethod}}</td>
        <td>{{i.onthlyCharges}}</td>
        <td>{{i.TotalCharges}}</td>
      </tr>
    {% endfor %}
    {% endif %}
    </tbody>
  </table>
</div>






{% endblock %}

webService/webService/webservice/clientchurn/templates/clientchurn/index.html
{% extends 'clientchurn/base.html' %}


{% block content %}

    <h1 class="intro-text text-center">Merci !</h1>

    <div class="container table-responsive fixed-table-body">
  <h2 class="text-center"><u>Liste des 50 premiers Clients </u></h2><br>
  <table class="table table-hover table-dark table-striped">
    <thead>
      <tr>
        <th>Numero Client</th>
        <th>Nom Client</th>
      </tr>
    </thead>
    <tbody>
    <!-- jinja2 Technique -->
    {% if d %}
    {% for i in d %}
      <tr>
        <td>{{i.index}}</td>
        <td>{{i.client}}</td>
      </tr>
    {% endfor %}
    {% endif %}
    </tbody>
  </table>
</div>


    <div>


        <div class="input-group mb-3">
            <div>
            </div>
            <h1></h1>
        </div>

{% endblock %}

webService/webService/webservice/clientchurn/templates/clientchurn/predictions.html
{% extends 'clientchurn/base.html' %}


{% block content %}




    <div class="card text-center">
  <div></div>

  <div class="card text-center">
    <div class="card-header">
      <h5>Numero du Client Pour la prediction</h5>
    </div>
    <form action="{% url 'clientchurn:resultat'%}" method="get">
      {% csrf_token %}
        <div class="card-body">
        <h5 class="card-title"></h5>
        <div class="d-grid gap-2 col-6 mx-auto">
          <!------>

          <div>
            <input
              class="form-control-lg"
              id="formFileLg"
              type="number"
              name="custumer_id"
            />
            <div>
              <p>
                <input
                  class="btn btn-outline-success btn-lg"
                  style="margin: 10px; padding-left: 30px; padding-right: 30px"
                  type="submit"
                  name="pred"
                />
              </p>
            </div>
          </div>

          <!---->
        </div>
      </div>
    </form>


  </div>
</div>





        <div>{% include 'clientchurn/resultat.html' %}</div>


    </div>




{% endblock %}

webService/webService/webservice/clientchurn/templates/clientchurn/resultat.html
{% block content %}

    <div class="card text-center">
      <div class="card-header">
        <h3>RESULTAT DE LA PRÉDICTION</h3>
        <h4>{{ prediction }}</h4>
      </div>

      <div class="card-body">
        <h5 class="card-title"></h5>
        <div class="d-grid gap-2 col-6 mx-auto">
          <!--<a class="btn btn-outline-warning" type="button" href="#"
            >APPERCUE DES DONNEE SCRAPER
          </a>-->
          <p class="card-text"></p>
        </div>
      </div>
      <div class="card-footer text-muted"></div>
    </div>

{% endblock %}